spring:
  profiles:
    active: ${profile.active}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds0?characterEncoding=utf-8&useSSL=false
        username: root
        password: 111111


server:
  port: 8081

mytest:
  name: ${ace.name}

yml-properties:
  stringKey: stringKey
  integerKey: 1
  arrayKey:
    - item1
    - item2
    - item3